version: '3'

services:

  app-server:
    image: ymapi:${APP_IMAGE_VERSION}
    build:
      context: ./
      args:
        JAR_FILE: /target/yandex_market_api-${APP_BUILD_VERSION}.jar

    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_PORT=27017
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - RABBIT_HOST=rabbit
    ports:
      - 8089:8080
    restart: always
    depends_on:
      - mongodb
      - rabbitMQ
    networks:
      - backend

  mongodb:
    image: bitnami/mongodb:latest
    expose:
      - 27017
      - 27018
      - 27019
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DB}
    volumes:
      - "mogodb:/bitnami/mongodb"
    networks:
      backend:
        aliases:
          - "mongodb"

  rabbitMQ:
    image: rabbitmq:3-alpine
    expose:
      - 5672
    restart: always
    networks:
      backend:
        aliases:
          - "rabbit"

  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: temporary_password
  #    networks:
  #      - backend

volumes:
  mogodb:
networks:
  backend:
    driver: bridge