version: '3'

services:

  app-server:
    image: ymapi:${APP_IMAGE_VERSION}
    build:
      context: ./
      args:
        JAR_FILE: /target/yandex_market_api-${APP_BUILD_VERSION}.jar

    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_PORT=27017
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - RABBIT_HOST=rabbit
    ports:
      - 127.0.0.1:8089:8080
    restart: always
    depends_on:
      - mongodb
      - rabbitMQ
    networks:
      - backend


  mongodb-fix-permissions:
    image: 'alpine:latest'
    user: 0:0
    command: chmod -R 0777 /bitnami
    volumes:
      - ./mongodb_data:/bitnami

  mongodb:
    image: bitnami/mongodb:latest
    expose:
      - 27017
      - 27018
      - 27019
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DB}
    volumes:
      - ./mongodb_data:/bitnami/mongodb:rw
    depends_on:
      - mongodb-fix-permissions
    networks:
      backend:
        aliases:
          - "mongodb"

  rabbitMQ:
    image: rabbitmq:3-alpine
    expose:
      - 5672
    restart: always
    networks:
      backend:
        aliases:
          - "rabbit"


volumes:
  mongodb:
networks:
  backend:
    driver: bridge
