services:

  app-server:
    image: ymapi:${APP_IMAGE_VERSION}
    build:
      context: ./../
        args:
          JAR_FILE: target/yandex_market_api-${APP_BUILD_VERSION}.jar

    working_dir: /app
    volumes:
      - ./../:/app
    command: mvn clean spring-boot:run
    environment:
      - MONGO_URI=mongodb://mongodbYMAPI
      - RABBIT_URI=amqp://rabbitYMAPI
    ports:
      - 8089:8080
    restart: always
    depends_on:
      - mongodb
      - rabbitMQ
    networks:
      - backend

  mongodb:
    image: mongo:latest
    expose:
      - 27017
      - 27018
      - 27019
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temporary_password
    volumes:
      - "db_data:/data/db"
    networks:
      backend:
        aliases:
          - "mongodbYMAPI"

  rabbitMQ:
    image: rabbitmq:3-alpine
    expose:
      - 5672
    restart: always
    networks:
      backend:
        aliases:
          - "rabbitYMAPI"

  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: temporary_password
  #    networks:
  #      - backend

volumes:
  db_data:
networks:
  backend:
    driver: bridge